name: Bank
version: 0.1
main: net.bank.main.Main
author: GeroRobin
commands:
   eco:
      name: eco
      description: Zeigt deinen aktuellen Kontostand.
   givemoney:
      name: givemoney
      description: Gibt dir Geld.