name: Bank
version: 0.1
main: net.bank.main.Main
author: GeroRobin
api-version: 1.14
commands:
   eco:
      name: eco
      description: Zeigt deinen aktuellen Kontostand.
   givemoney:
      name: givemoney
      description: Gibt dir Geld.
   pay:
      name: pay
      description: Zahlt Geld an den angegeben Spieler.